---
title: "Get Securites Data from Internet"
output: html_notebook
---

## The `tseries` Package

This package has a `get.hist.quote` function

```{r}
library(tseries)
get.hist.quote(instrument = 'GOOG', quote='Adj', start='2011-02-09', end='2015-02-09')
```

## The `yahoo-finance` package

Python has a similar package to get data from yahoa finance

```{python}
import yfinance as yf
yahoo = yf.Ticker('MSFT')
print(yahoo.history('2011-02-09', '2015-02-09')[-1])
```
## Import Data from Internet Using Python

```{python}
import os
import pandas as pd
from datetime import datetime
from yahoo_finance import Share


def get_hk_stock_symbols(file_path):
    df = pd.read_csv(file_path, header=None,
                     names=['id', 'sym', 'name_zh', 'name_cn'],
                     dtype={
                         'sym': str
                     })
    df = df[df['sym'].str.startswith('0')]
    df['sym'] = df['sym'].str.extract('(?P<digital>[\d]{4}$)', expand=False)
    df['sym'] = df['sym'].astype(str) + '.HK'
    return df['sym'].tolist()


def create_dirs(dir):
    home_dir = os.path.expanduser('~')
    main_dir = os.path.join(home_dir, 'stock_data', dir)
    if not os.path.exists(main_dir):
        os.makedirs(main_dir)
    return main_dir


def get_prices(symbols, start, end, folder_name='hk'):
    cache_dir = create_dirs(folder_name)

    def get_prices_for(sym):
        stock_handler = Share(sym)
        try:
            print('# Getting data for {}...'.format(sym))
            data = stock_handler.get_historical(start, end)
            df = pd.DataFrame.from_dict(data)
            df.to_csv(os.path.join(cache_dir, sym))
            return sym, data
        except:
            print('# Error in downloading {}'.format(sym))
            return None

    jobs = [gevent.spawn(get_prices_for, sym) for sym in symbols]
    gevent.joinall(jobs)

symbols = get_hk_stock_symbols(os.path.join(os.getcwd(), 'hk_securities.csv'))
get_prices(symbols, '2010-01-01', datetime.now().strftime('%Y-%m-%d'))
```

## Concat all stock prices data into a single csv file

```{r}
library(tidyverse)
library(readr)
library(purrr)
library(stringr)

read_ticker_csv <- function (fpath) {
    ticker_symbol <- str_replace(basename(fpath), '.csv', '')
    read_csv(fpath) %>%
        mutate(Symbol = ticker_symbol) %>%
        select(Symbol, everything())
}

all_tickers <- 
    list.files('~/stock_data/hk/', pattern = '*.csv', full.names = TRUE) %>%
    map(read_ticker_csv) %>%
    reduce(rbind)

write_csv(all_tickers, path = '~/stock_data/2019-12_hk_stock_prices.csv')
```
